trigger:
  - main

pool:
  vmImage: 'windows-latest'
  name: 'Build'
  
variables:
  - group: GitHubSecrets  # New variable group for GitHub credentials

jobs:
  - job: MirrorRepo
    displayName: 'Mirror Azure DevOps Repo to GitHub'

    steps:
      # Step 1: Install Git (if not already available)
      - script: |
          git --version
        displayName: 'Check Git Version'

      # Step 2: Configure Git User
      - script: |
          git config --global user.name "berrones"
          git config --global user.email "adam.berrones@ky.gov"
        displayName: 'Configure Git User'

      # Step 3: Add GitHub as Remote and Push Changes
      - script: |
          git remote add mirror https://$(GITHUB_USERNAME):$(GITHUB_PAT)@github.com/KentuckyDepartmentForPublicHealth/PHT.git
          git fetch --unshallow || true
          git push --mirror mirror
        env:
          GITHUB_USERNAME: $(GITHUB_USERNAME)
          GITHUB_PAT: $(GITHUB_PAT)
        displayName: 'Mirror Repo to GitHub'
