trigger:
  - main

pool:
  vmImage: 'windows-latest'
  name: 'Build'

variables:
  - group: GitHubSecrets  # New variable group for GitHub credentials

jobs:
  - job: MirrorRepo
    displayName: 'Mirror Azure DevOps Repo to GitHub'
      
      - script: |
          git push mirror HEAD:main
        env:
          GITHUB_USERNAME: $(GITHUB_USERNAME)
          GITHUB_PAT: $(GITHUB_PAT)
        displayName: 'Mirror Repo to GitHub'