trigger:
  - main

pool:
  vmImage: 'windows-latest'
  name: 'Build'

variables:
  - group: GitHubSecrets  # Variable group for GitHub credentials

jobs:
  - job: MirrorRepo
    displayName: 'Mirror Azure DevOps Repo to GitHub'

    steps:
      # Step 1: Install Git (if not already available)
      - script: |
          git --version
        displayName: 'Check Git Version'

      # Step 2: Configure Git User
      - script: |
          git config --global user.name "$(GITHUB_USERNAME)"
          git config --global user.email "$(GITHUB_EMAIL)"
        displayName: 'Configure Git User'

      # Step 3: Set GitHub Remote URL with Credentials
      - script: |
          git remote set-url mirror https://$(GITHUB_USERNAME):$(GITHUB_PAT)@github.com/KentuckyDepartmentForPublicHealth/PHT.git
        displayName: 'Set GitHub Remote URL'

      # Step 4: Push Changes to GitHub
      - script: |
          git push mirror HEAD:main
        displayName: 'Mirror Repo to GitHub'
